services:
  - type: web
    name: kidoairaku
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SAKURA_API_TOKEN
        sync: false
